<template>
  <div class="p-4">
    <BasicTable @register="registerTable">
      <template #bodyCell="{ column, record }">
        <template v-if="column.dataIndex === 'mores'">
          <Button size="small" type="primary" @click="handleRemove(record, column)"> 删除</Button>
          <Button size="small" color="success"> 成功</Button>
          <Button size="small" color="warning"> 删除</Button>
        </template>
      </template>
    </BasicTable>
  </div>
</template>
<script lang="ts" setup>
import { useTable } from '@/components/Table';
import { searchFormSchema,columns } from "./formData"

const demoListApi = () => {
  return new Promise((resolve) => {
    resolve({
      "total": 1063,
      "current": 1,
      "size": 10,
      "code": 0,
      "list": [
        {
          "id": 1479,
          "classType": "创新",
          "kjType": "S",
          "lecture": 6,
          "year": "2024",
          "location": null,
          "subject": "数学",
          "grade": "G1",
          "lectureName": "美食总动员",
          "version": "1.1",
          "count": null,
          "challengeId": 30,
          "challengeName": "减法算式",
          "edition": "TEA",
          "type": 0,
          "typeName": "正式课-长期班",
          "uploadStatus": 1,
          "courseType": 0,
          "lockStatus": 0,
          "isOnline": 1,
          "knowledgeName": "默认知识点",
          "editTime": null,
          "keJianUrl": "https://app.thinkworldpro.com/get/url/kejian/Courseware2.0/index.html?type=test&kjId=1479&names=0&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxODgiLCJUYWciOiJSRUZfVE9LRU4iLCJVVUlEIjoiNzE3NzllMDAtYjM4NS00NTQ2LWJjYTEtODY1Y2MzM2JiYTgzIiwiZXhwIjoxNzE3MDYxOTY1LCJhY2NvdW50IjoiMTgzMjYwOTkwMjcifQ.KljdpJXk4nYntBqRNPXAJF2wWdvVEXIWSDiAo81LMj0",
          "keJianNamesUrl": null,
          "editStatus": null,
          "feedbackCount": 0,
          "feedbackTime": null,
          "feedbackStatus": 0,
          "topSort": 1,
          "urlType": 1,
          "url": "https://app.thinkworldpro.com/get/url/kejian/Courseware2.0/index.html?type=test&kjId="
        },
        {
          "id": 1390,
          "classType": "培优",
          "kjType": "S",
          "lecture": 11,
          "year": "2024",
          "location": null,
          "subject": "英语",
          "grade": "G1",
          "lectureName": "My family",
          "version": "1.0",
          "count": null,
          "challengeId": null,
          "challengeName": null,
          "edition": "TEA",
          "type": 0,
          "typeName": "正式课-长期班",
          "uploadStatus": 1,
          "courseType": 0,
          "lockStatus": 0,
          "isOnline": 1,
          "knowledgeName": "英语题目",
          "editTime": null,
          "keJianUrl": "https://app.thinkworldpro.com/get/url/kejian/Courseware2.0/index.html?type=test&kjId=1390&names=0&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxODgiLCJUYWciOiJSRUZfVE9LRU4iLCJVVUlEIjoiNzE3NzllMDAtYjM4NS00NTQ2LWJjYTEtODY1Y2MzM2JiYTgzIiwiZXhwIjoxNzE3MDYxOTY1LCJhY2NvdW50IjoiMTgzMjYwOTkwMjcifQ.KljdpJXk4nYntBqRNPXAJF2wWdvVEXIWSDiAo81LMj0",
          "keJianNamesUrl": null,
          "editStatus": null,
          "feedbackCount": 0,
          "feedbackTime": null,
          "feedbackStatus": 0,
          "topSort": 1,
          "urlType": 1,
          "url": "https://app.thinkworldpro.com/get/url/kejian/Courseware2.0/index.html?type=test&kjId="
        },
        {
          "id": 1389,
          "classType": "培优",
          "kjType": "S",
          "lecture": 10,
          "year": "2024",
          "location": null,
          "subject": "英语",
          "grade": "G1",
          "lectureName": "My family",
          "version": "1.0",
          "count": null,
          "challengeId": null,
          "challengeName": null,
          "edition": "TEA",
          "type": 0,
          "typeName": "正式课-长期班",
          "uploadStatus": 1,
          "courseType": 0,
          "lockStatus": 0,
          "isOnline": 1,
          "knowledgeName": "英语题目",
          "editTime": null,
          "keJianUrl": "https://app.thinkworldpro.com/get/url/kejian/Courseware2.0/index.html?type=test&kjId=1389&names=0&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxODgiLCJUYWciOiJSRUZfVE9LRU4iLCJVVUlEIjoiNzE3NzllMDAtYjM4NS00NTQ2LWJjYTEtODY1Y2MzM2JiYTgzIiwiZXhwIjoxNzE3MDYxOTY1LCJhY2NvdW50IjoiMTgzMjYwOTkwMjcifQ.KljdpJXk4nYntBqRNPXAJF2wWdvVEXIWSDiAo81LMj0",
          "keJianNamesUrl": null,
          "editStatus": null,
          "feedbackCount": 0,
          "feedbackTime": null,
          "feedbackStatus": 0,
          "topSort": 1,
          "urlType": 1,
          "url": "https://app.thinkworldpro.com/get/url/kejian/Courseware2.0/index.html?type=test&kjId="
        },
        {
          "id": 1388,
          "classType": "培优",
          "kjType": "S",
          "lecture": 9,
          "year": "2024",
          "location": null,
          "subject": "英语",
          "grade": "G1",
          "lectureName": "Where’s Monty?",
          "version": "1.0",
          "count": null,
          "challengeId": null,
          "challengeName": null,
          "edition": "TEA",
          "type": 0,
          "typeName": "正式课-长期班",
          "uploadStatus": 1,
          "courseType": 0,
          "lockStatus": 0,
          "isOnline": 1,
          "knowledgeName": "英语题目",
          "editTime": null,
          "keJianUrl": "https://app.thinkworldpro.com/get/url/kejian/Courseware2.0/index.html?type=test&kjId=1388&names=0&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxODgiLCJUYWciOiJSRUZfVE9LRU4iLCJVVUlEIjoiNzE3NzllMDAtYjM4NS00NTQ2LWJjYTEtODY1Y2MzM2JiYTgzIiwiZXhwIjoxNzE3MDYxOTY1LCJhY2NvdW50IjoiMTgzMjYwOTkwMjcifQ.KljdpJXk4nYntBqRNPXAJF2wWdvVEXIWSDiAo81LMj0",
          "keJianNamesUrl": null,
          "editStatus": null,
          "feedbackCount": 0,
          "feedbackTime": null,
          "feedbackStatus": 0,
          "topSort": 1,
          "urlType": 1,
          "url": "https://app.thinkworldpro.com/get/url/kejian/Courseware2.0/index.html?type=test&kjId="
        },
        {
          "id": 1387,
          "classType": "培优",
          "kjType": "S",
          "lecture": 8,
          "year": "2024",
          "location": null,
          "subject": "英语",
          "grade": "G1",
          "lectureName": "Where’s the ball?",
          "version": "1.0",
          "count": null,
          "challengeId": null,
          "challengeName": null,
          "edition": "TEA",
          "type": 0,
          "typeName": "正式课-长期班",
          "uploadStatus": 1,
          "courseType": 0,
          "lockStatus": 0,
          "isOnline": 1,
          "knowledgeName": "英语题目",
          "editTime": null,
          "keJianUrl": "https://app.thinkworldpro.com/get/url/kejian/Courseware2.0/index.html?type=test&kjId=1387&names=0&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxODgiLCJUYWciOiJSRUZfVE9LRU4iLCJVVUlEIjoiNzE3NzllMDAtYjM4NS00NTQ2LWJjYTEtODY1Y2MzM2JiYTgzIiwiZXhwIjoxNzE3MDYxOTY1LCJhY2NvdW50IjoiMTgzMjYwOTkwMjcifQ.KljdpJXk4nYntBqRNPXAJF2wWdvVEXIWSDiAo81LMj0",
          "keJianNamesUrl": null,
          "editStatus": null,
          "feedbackCount": 0,
          "feedbackTime": null,
          "feedbackStatus": 0,
          "topSort": 1,
          "urlType": 1,
          "url": "https://app.thinkworldpro.com/get/url/kejian/Courseware2.0/index.html?type=test&kjId="
        },
        {
          "id": 1386,
          "classType": "培优",
          "kjType": "S",
          "lecture": 7,
          "year": "2024",
          "location": null,
          "subject": "英语",
          "grade": "G1",
          "lectureName": "My toys",
          "version": "1.0",
          "count": null,
          "challengeId": null,
          "challengeName": null,
          "edition": "TEA",
          "type": 0,
          "typeName": "正式课-长期班",
          "uploadStatus": 1,
          "courseType": 0,
          "lockStatus": 0,
          "isOnline": 1,
          "knowledgeName": "英语题目",
          "editTime": null,
          "keJianUrl": "https://app.thinkworldpro.com/get/url/kejian/Courseware2.0/index.html?type=test&kjId=1386&names=0&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxODgiLCJUYWciOiJSRUZfVE9LRU4iLCJVVUlEIjoiNzE3NzllMDAtYjM4NS00NTQ2LWJjYTEtODY1Y2MzM2JiYTgzIiwiZXhwIjoxNzE3MDYxOTY1LCJhY2NvdW50IjoiMTgzMjYwOTkwMjcifQ.KljdpJXk4nYntBqRNPXAJF2wWdvVEXIWSDiAo81LMj0",
          "keJianNamesUrl": null,
          "editStatus": null,
          "feedbackCount": 0,
          "feedbackTime": null,
          "feedbackStatus": 0,
          "topSort": 1,
          "urlType": 1,
          "url": "https://app.thinkworldpro.com/get/url/kejian/Courseware2.0/index.html?type=test&kjId="
        },
        {
          "id": 1385,
          "classType": "培优",
          "kjType": "S",
          "lecture": 6,
          "year": "2024",
          "location": null,
          "subject": "英语",
          "grade": "G1",
          "lectureName": "My school",
          "version": "1.0",
          "count": null,
          "challengeId": null,
          "challengeName": null,
          "edition": "TEA",
          "type": 0,
          "typeName": "正式课-长期班",
          "uploadStatus": 1,
          "courseType": 0,
          "lockStatus": 0,
          "isOnline": 1,
          "knowledgeName": "英语题目",
          "editTime": null,
          "keJianUrl": "https://app.thinkworldpro.com/get/url/kejian/Courseware2.0/index.html?type=test&kjId=1385&names=0&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxODgiLCJUYWciOiJSRUZfVE9LRU4iLCJVVUlEIjoiNzE3NzllMDAtYjM4NS00NTQ2LWJjYTEtODY1Y2MzM2JiYTgzIiwiZXhwIjoxNzE3MDYxOTY1LCJhY2NvdW50IjoiMTgzMjYwOTkwMjcifQ.KljdpJXk4nYntBqRNPXAJF2wWdvVEXIWSDiAo81LMj0",
          "keJianNamesUrl": null,
          "editStatus": null,
          "feedbackCount": 0,
          "feedbackTime": null,
          "feedbackStatus": 0,
          "topSort": 1,
          "urlType": 1,
          "url": "https://app.thinkworldpro.com/get/url/kejian/Courseware2.0/index.html?type=test&kjId="
        },
        {
          "id": 1384,
          "classType": "培优",
          "kjType": "S",
          "lecture": 5,
          "year": "2024",
          "location": null,
          "subject": "英语",
          "grade": "G1",
          "lectureName": "Let’s colour",
          "version": "1.0",
          "count": null,
          "challengeId": null,
          "challengeName": null,
          "edition": "TEA",
          "type": 0,
          "typeName": "正式课-长期班",
          "uploadStatus": 1,
          "courseType": 0,
          "lockStatus": 1,
          "isOnline": 1,
          "knowledgeName": "英语题目",
          "editTime": null,
          "keJianUrl": "https://app.thinkworldpro.com/get/url/kejian/Courseware2.0/index.html?type=test&kjId=1384&names=0&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxODgiLCJUYWciOiJSRUZfVE9LRU4iLCJVVUlEIjoiNzE3NzllMDAtYjM4NS00NTQ2LWJjYTEtODY1Y2MzM2JiYTgzIiwiZXhwIjoxNzE3MDYxOTY1LCJhY2NvdW50IjoiMTgzMjYwOTkwMjcifQ.KljdpJXk4nYntBqRNPXAJF2wWdvVEXIWSDiAo81LMj0",
          "keJianNamesUrl": null,
          "editStatus": null,
          "feedbackCount": 0,
          "feedbackTime": null,
          "feedbackStatus": 0,
          "topSort": 1,
          "urlType": 1,
          "url": "https://app.thinkworldpro.com/get/url/kejian/Courseware2.0/index.html?type=test&kjId="
        },
        {
          "id": 1383,
          "classType": "培优",
          "kjType": "S",
          "lecture": 4,
          "year": "2024",
          "location": null,
          "subject": "英语",
          "grade": "G1",
          "lectureName": "The rainbow",
          "version": "1.0",
          "count": null,
          "challengeId": null,
          "challengeName": null,
          "edition": "TEA",
          "type": 0,
          "typeName": "正式课-长期班",
          "uploadStatus": 1,
          "courseType": 0,
          "lockStatus": 1,
          "isOnline": 1,
          "knowledgeName": "英语题目",
          "editTime": null,
          "keJianUrl": "https://app.thinkworldpro.com/get/url/kejian/Courseware2.0/index.html?type=test&kjId=1383&names=0&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxODgiLCJUYWciOiJSRUZfVE9LRU4iLCJVVUlEIjoiNzE3NzllMDAtYjM4NS00NTQ2LWJjYTEtODY1Y2MzM2JiYTgzIiwiZXhwIjoxNzE3MDYxOTY1LCJhY2NvdW50IjoiMTgzMjYwOTkwMjcifQ.KljdpJXk4nYntBqRNPXAJF2wWdvVEXIWSDiAo81LMj0",
          "keJianNamesUrl": null,
          "editStatus": null,
          "feedbackCount": 0,
          "feedbackTime": null,
          "feedbackStatus": 0,
          "topSort": 1,
          "urlType": 1,
          "url": "https://app.thinkworldpro.com/get/url/kejian/Courseware2.0/index.html?type=test&kjId="
        },
        {
          "id": 1382,
          "classType": "培优",
          "kjType": "S",
          "lecture": 3,
          "year": "2024",
          "location": null,
          "subject": "英语",
          "grade": "G1",
          "lectureName": "My friends",
          "version": "1.0",
          "count": null,
          "challengeId": null,
          "challengeName": null,
          "edition": "TEA",
          "type": 0,
          "typeName": "正式课-长期班",
          "uploadStatus": 1,
          "courseType": 0,
          "lockStatus": 0,
          "isOnline": 1,
          "knowledgeName": "英语题目",
          "editTime": null,
          "keJianUrl": "https://app.thinkworldpro.com/get/url/kejian/Courseware2.0/index.html?type=test&kjId=1382&names=0&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxODgiLCJUYWciOiJSRUZfVE9LRU4iLCJVVUlEIjoiNzE3NzllMDAtYjM4NS00NTQ2LWJjYTEtODY1Y2MzM2JiYTgzIiwiZXhwIjoxNzE3MDYxOTY1LCJhY2NvdW50IjoiMTgzMjYwOTkwMjcifQ.KljdpJXk4nYntBqRNPXAJF2wWdvVEXIWSDiAo81LMj0",
          "keJianNamesUrl": null,
          "editStatus": null,
          "feedbackCount": 0,
          "feedbackTime": null,
          "feedbackStatus": 0,
          "topSort": 1,
          "urlType": 1,
          "url": "https://app.thinkworldpro.com/get/url/kejian/Courseware2.0/index.html?type=test&kjId="
        }
      ]
    })
  })
}

const resetFuncs = async () => {
  return new Promise(resolve => {
    resolve('success')
  })
}



const [registerTable] = useTable({
  title: 'TableAction组件及固定列示例',
  api: demoListApi,
  columns: columns,
  bordered: true,
  formConfig: {
    labelWidth: 120,
    schemas: searchFormSchema,
    autoSubmitOnEnter: true,
    showAdvancedButton: true,
    autoAdvancedLine: 4,
    showSubmitButton: false,
    resetFunc: resetFuncs,

  },
  useSearchForm: true,
  showTableSetting: true,
  // actionColumn: {
  //   width: 250,
  //   title: 'Action',
  //   dataIndex: 'action',
  //   // slots: { customRender: 'action' },
  // },
});
function handleRemove(record: Recordable, column) {
  console.log('点击了编辑', record);
  console.log('点击了编辑 column', column);
}


</script>